# Generated by Django 3.2.12 on 2022-03-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('event', models.CharField(max_length=50)),
                ('parameters', models.JSONField()),
                ('event_datetime', models.DateTimeField()),
            ],
        ),
    ]
